"""empty message

Revision ID: 677141915561
Revises: 66fe6d77807a
Create Date: 2019-11-07 19:05:58.426241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '677141915561'
down_revision = '66fe6d77807a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gate',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gmt_create', sa.DateTime(), nullable=True),
    sa.Column('gmt_modified', sa.DateTime(), nullable=True),
    sa.Column('course', sa.String(length=100), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('answer', sa.String(length=255), nullable=True),
    sa.Column('topic_raw', sa.Text(), nullable=True),
    sa.Column('answer_raw', sa.Text(), nullable=True),
    sa.Column('remark', sa.String(length=255), nullable=True),
    sa.Column('related_pic', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('last_edit', sa.String(length=30), nullable=True))
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=30),
               nullable=True)
    op.drop_column('user', 'last_edit')
    op.drop_table('gate')
    # ### end Alembic commands ###
