"""empty message

Revision ID: 7ddfa62e73b3
Revises: a883fea4d8e7
Create Date: 2019-01-06 02:42:05.112777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ddfa62e73b3'
down_revision = 'a883fea4d8e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gate', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'gate', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'gate', type_='foreignkey')
    op.drop_column('gate', 'user_id')
    # ### end Alembic commands ###
