"""empty message

Revision ID: 8ec8877cf4a5
Revises: 66bba45fbefe
Create Date: 2019-11-18 16:07:57.996199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ec8877cf4a5'
down_revision = '66bba45fbefe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config', sa.Column('others', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config', 'others')
    # ### end Alembic commands ###
