"""empty message

Revision ID: eb0e88b53190
Revises: 677141915561
Create Date: 2019-11-12 22:02:45.812664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb0e88b53190'
down_revision = '677141915561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensor',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('gmt_create', sa.DateTime(), nullable=True),
    sa.Column('gmt_modified', sa.DateTime(), nullable=True),
    sa.Column('sensor_type', sa.String(length=100), nullable=True),
    sa.Column('sensor_data', sa.BigInteger(), nullable=True),
    sa.Column('others', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sensor')
    # ### end Alembic commands ###
